### PR TITLE
chore: upgrade to angular and nx 13

### PR DESCRIPTION
**Pull request by billyjov**

### CODE REVIEW

**Comment by BioPhoton** [comment]
Thanks a lot for this lift! ❤❤❤❤❤

**Comment by codoffer** [comment]
@BioPhoton Have created a new release? How can I use this patch?

**Comment by billyjov** [comment]
@codoffer No the release was not created yet. Maybe in de next days.

**Comment by robjean9** [comment]
@BioPhoton @billyjov you pretend release the support for angular 13 on npm?

**Comment by billyjov** [comment]
@robjean9 Yes we are looking forward to do this soon. There are a few things we want to automate before this.

**Pull request merged**
